shared:
  image: gcc:latest
  environment:
    SD_COVERAGE_PLUGIN_ENABLED: "false"

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - build_binary: c++ -std=c++17 src/main.cpp src/Process.cpp -o tmp/mini_supervisor_test
      - run_app: tmp/mini_supervisor_test